REQUIRED PACKAGES

In [1]:
import pandas as pd                           
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ADDING DATASET

In [2]:
dw_df=pd.read_csv("delhi.csv")

TOP 5 ROWS

In [3]:
dw_df.head(5)

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,moonrise,moonset,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,2009-01-01 00:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,14,19,0,50,0.0,1016,10,10,331,12
1,2009-01-01 01:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,13,21,0,51,0.0,1016,10,10,329,13
2,2009-01-01 02:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,12,22,0,52,0.0,1016,9,10,327,13
3,2009-01-01 03:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,11,23,0,54,0.0,1016,9,10,326,13
4,2009-01-01 04:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,11,21,2,52,0.0,1016,9,10,318,13

BOTTOM 5 ROWS

In [4]:
dw_df.tail(5)

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,moonrise,moonset,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
96427,2020-01-01 19:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,17,11,10,39,0.0,1020,17,10,96,9
96428,2020-01-01 20:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,16,11,9,40,0.0,1021,16,10,97,8
96429,2020-01-01 21:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,16,12,8,41,0.0,1021,16,10,98,8
96430,2020-01-01 22:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,15,11,8,42,0.0,1021,15,10,96,8
96431,2020-01-01 23:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,15,10,7,42,0.0,1022,15,10,94,8

DATA INFO

In [5]:
dw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96432 entries, 0 to 96431
Data columns (total 25 columns):
date_time            96432 non-null object
maxtempC             96432 non-null int64
mintempC             96432 non-null int64
totalSnow_cm         96432 non-null float64
sunHour              96432 non-null float64
uvIndex              96432 non-null int64
uvIndex.1            96432 non-null int64
moon_illumination    96432 non-null int64
moonrise             96432 non-null object
moonset              96432 non-null object
sunrise              96432 non-null object
sunset               96432 non-null object
DewPointC            96432 non-null int64
FeelsLikeC           96432 non-null int64
HeatIndexC           96432 non-null int64
WindChillC           96432 non-null int64
WindGustKmph         96432 non-null int64
cloudcover           96432 non-null int64
humidity             96432 non-null int64
precipMM             96432 non-null float64
pressure             96432 non-null int64
tempC                96432 non-null int64
visibility           96432 non-null int64
winddirDegree        96432 non-null int64
windspeedKmph        96432 non-null int64
dtypes: float64(3), int64(17), object(5)
memory usage: 18.4+ MB

CHECKING FOR NULL ENTRIES

In [6]:
dw_df.isna().sum()

date_time            0
maxtempC             0
mintempC             0
totalSnow_cm         0
sunHour              0
uvIndex              0
uvIndex.1            0
moon_illumination    0
moonrise             0
moonset              0
sunrise              0
sunset               0
DewPointC            0
FeelsLikeC           0
HeatIndexC           0
WindChillC           0
WindGustKmph         0
cloudcover           0
humidity             0
precipMM             0
pressure             0
tempC                0
visibility           0
winddirDegree        0
windspeedKmph        0
dtype: int64

CHECKING FOR UNIQUE VALUES

In [7]:
dw_df.nunique(axis=0)

date_time            96432
maxtempC                39
mintempC                43
totalSnow_cm             1
sunHour                 62
uvIndex                  9
uvIndex.1               11
moon_illumination      101
moonrise              1331
moonset               1360
sunrise                114
sunset                 120
DewPointC               48
FeelsLikeC              61
HeatIndexC              60
WindChillC              51
WindGustKmph            65
cloudcover             101
humidity                99
precipMM                88
pressure                39
tempC                   52
visibility              21
winddirDegree          361
windspeedKmph           42
dtype: int64

In [8]:
dw_df

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,moonrise,moonset,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,2009-01-01 00:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,14,19,0,50,0.0,1016,10,10,331,12
1,2009-01-01 01:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,13,21,0,51,0.0,1016,10,10,329,13
2,2009-01-01 02:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,12,22,0,52,0.0,1016,9,10,327,13
3,2009-01-01 03:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,11,23,0,54,0.0,1016,9,10,326,13
4,2009-01-01 04:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,11,21,2,52,0.0,1016,9,10,318,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96427,2020-01-01 19:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,17,11,10,39,0.0,1020,17,10,96,9
96428,2020-01-01 20:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,16,11,9,40,0.0,1021,16,10,97,8
96429,2020-01-01 21:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,16,12,8,41,0.0,1021,16,10,98,8
96430,2020-01-01 22:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,15,11,8,42,0.0,1021,15,10,96,8
96431,2020-01-01 23:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,...,15,10,7,42,0.0,1022,15,10,94,8

SINCE "date_time" HAS ALL UNIQUE VALUE THEREFORE SETTING IT AS THE INDEX

In [9]:
dw_df.set_index("date_time")

,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,moonrise,moonset,sunrise,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
date_time,,,,,,,,,,,,,,,,,,,,,
2009-01-01 00:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,07:14 AM,...,14,19,0,50,0.0,1016,10,10,331,12
2009-01-01 01:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,07:14 AM,...,13,21,0,51,0.0,1016,10,10,329,13
2009-01-01 02:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,07:14 AM,...,12,22,0,52,0.0,1016,9,10,327,13
2009-01-01 03:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,07:14 AM,...,11,23,0,54,0.0,1016,9,10,326,13
2009-01-01 04:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,07:14 AM,...,11,21,2,52,0.0,1016,9,10,318,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-01 19:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,07:14 AM,...,17,11,10,39,0.0,1020,17,10,96,9
2020-01-01 20:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,07:14 AM,...,16,11,9,40,0.0,1021,16,10,97,8
2020-01-01 21:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,07:14 AM,...,16,12,8,41,0.0,1021,16,10,98,8
2020-01-01 22:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,07:14 AM,...,15,11,8,42,0.0,1021,15,10,96,8
2020-01-01 23:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,07:14 AM,...,15,10,7,42,0.0,1022,15,10,94,8

CHECKING THE SIZE AND COLUMN NAME

In [10]:
dw_df.shape #columns is still 25 that means need to change index in csv

(96432, 25)

In [11]:
dw_df=pd.read_csv("delhi.csv", parse_dates=["date_time"],index_col="date_time") #setting datetime format and it as index

In [12]:
dw_df

,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,moonrise,moonset,sunrise,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
date_time,,,,,,,,,,,,,,,,,,,,,
2009-01-01 00:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,07:14 AM,...,14,19,0,50,0.0,1016,10,10,331,12
2009-01-01 01:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,07:14 AM,...,13,21,0,51,0.0,1016,10,10,329,13
2009-01-01 02:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,07:14 AM,...,12,22,0,52,0.0,1016,9,10,327,13
2009-01-01 03:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,07:14 AM,...,11,23,0,54,0.0,1016,9,10,326,13
2009-01-01 04:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,07:14 AM,...,11,21,2,52,0.0,1016,9,10,318,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-01 19:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,07:14 AM,...,17,11,10,39,0.0,1020,17,10,96,9
2020-01-01 20:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,07:14 AM,...,16,11,9,40,0.0,1021,16,10,97,8
2020-01-01 21:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,07:14 AM,...,16,12,8,41,0.0,1021,16,10,98,8
2020-01-01 22:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,07:14 AM,...,15,11,8,42,0.0,1021,15,10,96,8
2020-01-01 23:00:00,19,10,0.0,8.7,5,1,37,11:28 AM,11:12 PM,07:14 AM,...,15,10,7,42,0.0,1022,15,10,94,8

In [13]:
dw_df.columns   #24 columns

Index(['maxtempC', 'mintempC', 'totalSnow_cm', 'sunHour', 'uvIndex',
       'uvIndex.1', 'moon_illumination', 'moonrise', 'moonset', 'sunrise',
       'sunset', 'DewPointC', 'FeelsLikeC', 'HeatIndexC', 'WindChillC',
       'WindGustKmph', 'cloudcover', 'humidity', 'precipMM', 'pressure',
       'tempC', 'visibility', 'winddirDegree', 'windspeedKmph'],
      dtype='object')

INFO ABOUT EACH COLUMN

In [14]:
dw_df.describe()

,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,DewPointC,FeelsLikeC,HeatIndexC,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
count,96432.000000,96432.000000,96432.0,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000
mean,32.681434,21.505475,0.0,11.213489,6.736685,4.390316,46.094077,12.170929,30.486270,30.608543,29.072569,11.983501,14.485119,41.323254,0.032072,1006.972333,26.672484,9.913307,214.948689,8.795151
std,7.479931,8.245626,0.0,2.155831,1.656212,3.372834,31.249725,8.049545,9.853813,9.708888,8.581811,6.182597,20.518663,21.351832,0.287923,7.789316,8.917470,0.992465,101.676151,4.329033
min,12.000000,1.000000,0.0,3.800000,3.000000,1.000000,0.000000,-22.000000,4.000000,5.000000,4.000000,0.000000,0.000000,2.000000,0.000000,987.000000,0.000000,0.000000,0.000000,0.000000
25%,26.000000,14.000000,0.0,8.700000,5.000000,1.000000,18.000000,6.000000,23.000000,24.000000,23.000000,7.000000,0.000000,24.000000,0.000000,1000.000000,20.000000,10.000000,116.000000,6.000000
50%,34.000000,23.000000,0.0,11.600000,7.000000,5.000000,46.000000,11.000000,31.000000,31.000000,30.000000,11.000000,5.000000,38.000000,0.000000,1007.000000,28.000000,10.000000,259.000000,8.000000
75%,38.000000,28.000000,0.0,13.200000,8.000000,8.000000,73.000000,20.000000,38.000000,38.000000,35.000000,16.000000,21.000000,56.000000,0.000000,1014.000000,33.000000,10.000000,303.000000,11.000000
max,52.000000,43.000000,0.0,14.000000,11.000000,11.000000,100.000000,30.000000,65.000000,65.000000,54.000000,72.000000,100.000000,100.000000,17.600000,1025.000000,51.000000,20.000000,360.000000,44.000000

In [15]:
import sklearn

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
%matplotlib inline